### ISSUE TITLE
樹狀圖結構沒有對齊

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#1]
如果head名稱超過一行(圈選部分)，第二行沒辦法和第一行對齊
![2](https://cloud.githubusercontent.com/assets/8033199/11925326/5de132a0-a7f5-11e5-9c01-0996a7d0ba46.JPG)

**Comment by km001** [comment]
請問所謂的對齊是第一行開頭文字跟第二行對齊嗎?能否給預期畫面的圖。

2015-12-21 15:52 GMT+08:00 rickie120243 notifications@github.com:

**Comment by rickie120243** [comment]
第二行開頭和第一行對齊
預期畫面如下(圈選部分)
![2](https://cloud.githubusercontent.com/assets/8033199/11927523/1c412bb2-a808-11e5-9633-634d5971fff6.JPG)
其餘畫面呈現方式和 http://demoshow.utrust.com.tw/adarsha/content.html# 相同

**Comment by ElaineChu-P** [comment]
您好，這個模組不是照著原本的prototype的結構，所以這邊我們需要跟Yap商量，討論是否可以在目前模組 增加class的方式，來調整目前的介面，謝謝!!

**Comment by yapcheahshen** [comment]
這個問題我已解決了(加text-align)，明天會請廣明更新。

大P notifications@github.com 於 2015年12月22日 下午5:23 寫道：

**Comment by km001** [comment]
已更新。請確認，謝謝。

**Comment by rickie120243** [comment]
剛剛pull adarsha2016，把隨身碟裡面的檔案覆蓋掉後執行，結果還是和原本一樣。
![image](https://cloud.githubusercontent.com/assets/8033199/11974373/a6feac06-a99e-11e5-8b6a-f87ea06d0c27.png)

**Comment by ElaineChu-P** [comment]
@rickie120243  您好，請問目前左邊目錄還有沒對齊的部分嗎?   @@
線上版預覽：http://adarsha.utrust.com.tw:92/adarsha2016/

**Comment by rickie120243** [comment]
是的(紅圈處)
![image](https://cloud.githubusercontent.com/assets/8033199/12262976/92b56154-b966-11e5-897f-e42371ba87ea.png)

使用者希望的結果如下圖(紅線為切齊後)
![image](https://cloud.githubusercontent.com/assets/8033199/12263063/3f3da62a-b967-11e5-91db-e27a83468328.png)

**Comment by rickie120243** [comment]
法海師說暫時不用處理
