### ISSUE TITLE
prevfile按鈕位置調整

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#16]
目前的prefile按鈕位置在藍框處
![image](https://cloud.githubusercontent.com/assets/8033199/12382933/d7e22104-bdda-11e5-921a-56695bed4e9a.png)

正確位置應該在下圖紅圈處(http://demoshow.utrust.com.tw/adarsha/content.html)
![image](https://cloud.githubusercontent.com/assets/8033199/12382979/4c74b3ba-bddb-11e5-878c-c251fd7f1ae3.png)

**Comment by ElaineChu-P** [comment]
![_012216_074936_pm](https://cloud.githubusercontent.com/assets/13374805/12509957/4e87fd92-c141-11e5-8542-ea628bf32021.jpg)

您好，因為設計雙欄可以開關的關係，導致切換上下檔案的按鈕<> 在css中無法固定位置，我們暫時先放置麵包屑的位置，再麻煩查看，如果有其他問題再一起討論，謝謝

http://adarsha.utrust.com.tw:92/adarsha2016
