### ISSUE TITLE
圖文按鈕error

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#19]
按圖文按鈕(紅圈)出現error
![image](https://cloud.githubusercontent.com/assets/8033199/12445976/695b9e6c-bfa2-11e5-8b77-2bcce117c04d.png)

**Comment by km001** [comment]
可否描述問題出現的情況?因為我這沒有辦法重現問題。

**Comment by rickie120243** [comment]
請問最近node_modules有更新嗎? 可能我們這邊build有問題

2016-01-21 10:34 GMT+08:00 km001 notifications@github.com:

**Comment by km001** [comment]
最近node_modules有不少更新 能的話請全部更新到最新版build後再確認 謝謝
