### ISSUE TITLE
內文音節符號(་)後面的空白鍵

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#2]
Hi 大家好:

有使用者回饋說內文中有些音節符號(་)後面有多一個空白鍵(下圖紅圈)，造成經文裡的句子不連貫
![4](https://cloud.githubusercontent.com/assets/8033199/11999377/2c3d275e-aaf7-11e5-8e6e-24ccec7ef1c4.JPG)

查驗後可能導致的原因如下:
由於數位經文的換行是根據實體經文而來，所以有些句子寫到一半會被強迫換行(下圖紅圈)
而應該是這些被強迫換行的句子，使得經文在adarsha中會在音節府號(་)後面多一個空白鍵
![5](https://cloud.githubusercontent.com/assets/8033199/11999287/9815327a-aaf5-11e5-9984-666c181c96e0.JPG)

希望的結果應該是把這些空白鍵移除，紅圈為目前狀況，藍圈為預期結果
![6](https://cloud.githubusercontent.com/assets/8033199/11999455/3c1734b0-aaf9-11e5-9241-748e25e4cafa.JPG)

謝謝

**Comment by yapcheahshen** [comment]
pc 版通常使用者會做剪貼的動作，
所以要在塗紅之後，將 \n 去掉。

rickie120243 notifications@github.com 於 2015年12月25日 上午11:21 寫道：
