### ISSUE TITLE
移除每個vol開頭的編號

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#20]
每個vol的開頭都有個編號(_@\d{1,2})
使用者不知道是甚麼意思，希望能夠移除
![image](https://cloud.githubusercontent.com/assets/8033199/12473375/ab215594-c04c-11e5-8c7d-a0c86cc25f05.png)

**Comment by km001** [comment]
請確認畫面 0f77ba67f43a92611ec04d91102055fb3a6b18ab

**Comment by rickie120243** [comment]
目前看到畫面是這樣
![image](https://cloud.githubusercontent.com/assets/8033199/12474123/73a1ff9a-c053-11e5-9833-c64d18f55549.png)
但瀏覽介面的sutra id 不見了
![image](https://cloud.githubusercontent.com/assets/8033199/12474138/934f043c-c053-11e5-920e-31935db340e5.png)

**Comment by km001** [comment]
因為認為麵包屑已有顯示sutraid，所以試著移除瀏覽介面的sutra id

**Comment by rickie120243** [comment]
好的
