### ISSUE TITLE
麵包屑頻次沒有立即更新

### ISSUE THREAD

**Issue by yapcheahshen** [karmapa/adarsha2016#21]
重現方式：
1)F5 refresh
2)輸入 ta
3)按麵包屑下拉，紅色數字未顯示
4)點一下搜尋結果，要到其他的卷。
5)此時麵包屑才會有紅色數字。
預期反應：
每次新搜尋，麵包屑應立刻更新。

**Comment by km001** [comment]
目前是否麵包屑與樹狀結構的數字都消失了?

**Comment by km001** [comment]
請確認 6ba0a99c98a273a4e66f8f06390ec50bac362a82

**Comment by yapcheahshen** [comment]
更新 ksana-simple-api@1.5.19

2016-01-22 16:28 GMT+08:00 km001 notifications@github.com:

**Comment by km001** [comment]
已更新
![4](https://cloud.githubusercontent.com/assets/14304067/12506629/713ffad0-c12b-11e5-89f6-c6ee33ddc87a.png)
