### ISSUE TITLE
一般搜尋欄位提示文字

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#23]
目錄 改成 Page No, Title Id, Catalog Search

全文 改成 Content Search

qqqq 改成
Wildcards Search Rule:
. (dot) and _(star) these two wildcards match single unknow syllable.
example: 
search:rdzogs.sangs/ རྫོགས.སངས(1 syllable in between)
result:
-->rdzogs pa’i sangs…../རྫོགས་པའི་སངས་་་་་་
-->rdgogs par sangs…../རྫོགས་པར་སངས་་་་་
example: 
search:rdzogs.2sangs/ རྫོགས.2སངས(2 syllable in between)
result:
-->rdzogs par/_/rdzogs sangs…../རྫོགས་པར། །རྫོགས་སངས་་་་་་
-->rdgogs/_/ngas ni sangs…../རྫོགས། །ངས་ནི་སངས་་་་་
example: 
search:rdzogs_sangs/ རྫོགས_སངས(1 or non syllable in between)
result:
-->rdzogs pa’i sangs…../རྫོགས་པའི་སངས་་་་་་
-->rdgogs sangs…../རྫོགས་སངས་་་་་
example:
search:de_3pa/དེ3*པ(1 or 2 or 3 or non syllable in between)
result:
-->de dag gis smras pa…./དེ་དག་གིས་སྨྲས་པ་་་་་་
-->de la smras pa.../དེ་ལ་སྨྲས་པ་་་་་
-->de gang yin pa…./དེ་གང་ཡིན་པ་་་་་་

預期結果如圖
![image](https://cloud.githubusercontent.com/assets/8033199/12506938/7285d7c8-c12d-11e5-8408-53fe97d46e6c.png)

**Comment by km001** [comment]
請確認 c6bea81dcf241666cb6a138ee0c0d50e879e8997
