### ISSUE TITLE
進階搜尋結果點選後出現error

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#24]
進階搜尋的結果目前發現sutraid 後面有英文的(ex. J8(m) )，點選結果會出現error
![image](https://cloud.githubusercontent.com/assets/8033199/12510323/04a22b14-c144-11e5-982e-8b433ce55b41.png)

**Comment by km001** [comment]
請確認 8d388e8bf1644e6567e9b9d64be48af380fea79c
