### ISSUE TITLE
一般搜尋輸入pb和經文內容無法顯示搜尋結果

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#26]
![image](https://cloud.githubusercontent.com/assets/8033199/12804371/a551b118-cb2d-11e5-9c14-133c7fe09834.png)

**Comment by km001** [comment]
目前輸入uti的話會直接跳轉至對應頁面。請問在這情況下搜尋結果是要呈現什麼?

**Comment by rickie120243** [comment]
實際輸入頁碼和內文的結果圖如下
先輸入頁碼，然後跳轉到該頁面
下面欄位再輸入關鍵字
![image](https://cloud.githubusercontent.com/assets/8033199/12805479/ad92cf98-cb36-11e5-896c-8083145d322c.png)
請問輸入完關鍵字後右邊內文能同時塗紅嗎?

**Comment by km001** [comment]
請問是像這樣嗎 d9bb1122b0ac8c4d7fa9fb0cb13669fd50d52f2b

**Comment by rickie120243** [comment]
是的 謝謝
