### ISSUE TITLE
搜尋未塗紅

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#6]
影片如下
https://www.youtube.com/watch?v=qiUWQ-HsURc&feature=youtu.be

搜尋完點下方搜尋結果，經文沒有塗紅

**Comment by km001** [comment]
2016/1/18 請刪暫存後再確認

**Comment by rickie120243** [comment]
點選的搜尋結果在當前瀏覽頁面，經文不會塗紅
但如果按了prevfile或nextfile，經文就有塗紅
再回到剛剛的當前瀏覽頁面，經文也變成有塗紅(影片如下)
https://www.youtube.com/watch?v=Ubf99Svouj0&feature=youtu.be

可能是搜尋完後當前瀏覽頁面沒有更新造成的

**Comment by km001** [comment]
2016/1/22 請再確認
