### ISSUE TITLE
圖文對照圖片顯示問題

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#7]
圖片在1:1顯示時有部分被切掉
![image](https://cloud.githubusercontent.com/assets/8033199/12087318/f5f40e38-b30c-11e5-806b-e1a71f75e40f.png)

應該要能顯示整張圖
![image](https://cloud.githubusercontent.com/assets/8033199/12087360/35f99958-b30d-11e5-9486-e48ddcb38090.png)

範例原圖連結:http://res.cloudinary.com/www-dharma-treasure-org/image/upload/lijiang/001/001-002a.jpg

**Comment by yapcheahshen** [comment]
text4image.js 

```
,resize:function(domnode){
    setTimeout(function(){
        domnode.iviewer("set_zoom", 100);
    },200);
}
```

改成這樣即可。
iviewer("update")會要求iviewer 重算最適框 
(視窗改動時也會呼叫，詳見 js/jquery.iviewer.js  279 行，$(window).resize 時會呼叫 update() )

```
,resize:function(domnode){
    setTimeout(function(){
        domnode.iviewer("update");  //重算最適框
        domnode.iviewer("fit", true);  //不設 100%，設為全圖顯示
    },200);
}
```
