### ISSUE TITLE
圖文對照經文顯示問題

### ISSUE THREAD

**Issue by rickie120243** [karmapa/adarsha2016#8]
該行經文如果太長，會超出螢幕範圍(紅圈處)
![image](https://cloud.githubusercontent.com/assets/8033199/12087428/d15523e0-b30d-11e5-9acd-440e42958740.png)

在小螢幕下問題更嚴重
![image](https://cloud.githubusercontent.com/assets/8033199/12087460/17f1b534-b30e-11e5-828f-d227eb97af12.png)

**Comment by rickie120243** [comment]
目前看到的模式
![image](https://cloud.githubusercontent.com/assets/8033199/12389144/0aa3c71e-be12-11e5-833a-84740dc08fbf.png)

使用者期望的結果如下圖
第二行經文過長所以折行(藍圈處)，第三行(第二行過長的部分)最後依舊照著圖片的經文換行(紅圈處)
![image](https://cloud.githubusercontent.com/assets/8033199/12389342/02e740ea-be13-11e5-8d59-77f10987e3a4.png)

**Comment by km001** [comment]
請確認 7ab02d4065fb8b78126312c9d889e1089c95715d
